# Generated by Django 2.2 on 2020-01-31 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_userprofileregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileregister',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
